### ISSUE TITLE
Adding multiple sinks

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/sink-map#9]
It would be nice to have shorthand method(s) to add multiple sinks at once.

Accepting another map

```js
import { parsers } from '@rdfjs/formats-common'
import existingMap from './parsers'

existingMap.addAll(parsers)
```

Accepting a JS hashmap

```js
import N3Parser from '@rdfjs/parser-n3'
import existingMap from './parsers'

existingMap.addAll({
  'text/turtle': new N3Parser()
})
```

And maybe an array to align with Map ctor

```js
import N3Parser from '@rdfjs/parser-n3'
import existingMap from './parsers'

existingMap.addAll([
  ['text/turtle': new N3Parser()]
])
```

**Comment by bergos** [comment]
@tpluscode Is there any proposal for the plain JS `Map` that would add the functionality? I would like to keep it as close as possible in sync with the standard `Map` class. If there is nothing coming, I would propose to use a chain of `.set()`. Otherwise we could add it to our code, so we don't need to rely on the `Map` implementation.

**Comment by bergos** [comment]
It looks like [Map.prototype.merge](https://tc39.es/proposal-collection-methods/#Map.prototype.merge) would be the correct method in the proposal for new methods for collections. But since there have been [no updates for about four years](https://github.com/tc39/proposal-collection-methods/issues/45), I will close this issue. Once the TC39 proposal status changes, we can open this issue again.
